### ISSUE TITLE
Add LLM base url to config

### ISSUE THREAD

**Issue by matthoffner** [failfa-st/hyv#7]
To unlock local LLaMa support I'd like to be able to set the base url in config like the API key.

**Comment by pixelass** [comment]
That sounds lik something that would be done in theadapter (see our automatic1111 adapter: https://github.com/failfa-st/hyv/blob/main/packages/stable-diffusion/src/automatic1111.ts#L36-L41)

I am working on an oogabooga adapter that works very similar (local tests already exist)

I hope this answers your question, or gives you some insight.

**Comment by pixelass** [comment]
@matthoffner how are you planning to use LLMs aside from GPT? I will release an [oogabooga](https://github.com/oobabooga/text-generation-webui) adapter pretty soon (with in the next week) but I'm interested in your thoughts.

**Comment by matthoffner** [comment]
I don't really have any specific plans other than trying examples with my best local LLM to compare.

I'm typically just firing up a llama-cpp-python server. (https://github.com/abetlen/llama-cpp-python) LocalAI (https://github.com/go-skynet/LocalAI) is another option that matches the OpenAI api spec. 

I'm not using oogabooga, its a gradio frontend so I don't know how it would work with hyv but I haven't been following the project closely. 

For model testing I've forked the chatbot-ui https://huggingface.co/spaces/matthoffner/chatbot with a custom base url.

**Comment by pixelass** [comment]
So, Hyv is just a library that makes streamlining content from different AIs easier. That means, that you can just write an adapter for whatever you need. I'm currently working on better docs that will shed a bit more light on using Hyv beyond the built-in adapters. The GPTModelAdapter (and especially the upcoming oogabooga adapter) are a good starting point. Oogabooga just serves as an API so it is most likely very similar to the adapter that you need.

**Comment by pixelass** [comment]
Closing this since there are now extensive docs
